language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - DJANGO=stable/1.7.x
  - DJANGO=stable/1.8.x
  - DJANGO=master

install:
  - pip install https://github.com/django/django/archive/${DJANGO}.tar.gz
  - pip install -e .
  - pip install -r tests/requirements.txt
  - pip install codecov

script:
  - ./tests/runtests.sh

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO=master
    - python: "3.3"
      env: DJANGO=master

  allow_failures:
    - env: DJANGO=master

after_success:
    codecov
